### ISSUE TITLE
ValueError: y has 0 samples

### ISSUE THREAD

**Issue by MohdSafwanAhmad** [shubham0204/Bounding_Box_Regression_TF#3]
Hey Shubham, I cloned the rep and tried running DataProcessor.py but I'm getting the following error:

```
Traceback (most recent call last):
  File "DataProcessor.py", line 39, in <module>
    classes_onehot = encoder.fit_transform( classes )
  File "/home/safwan/anaconda3/envs/project1/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 436, in fit_transform
    return self.fit(y).transform(y)
  File "/home/safwan/anaconda3/envs/project1/lib/python3.7/site-packages/sklearn/preprocessing/label.py", line 410, in fit
    raise ValueError('y has 0 samples: %r' % y)
ValueError: y has 0 samples: array([], dtype=float64) 
```
Could you suggest what might be the problem?

**Comment by MohdSafwanAhmad** [comment]
I have checked all the folders and dataset folder as well.

**Comment by Harshithasriniv** [comment]
Hi @MohdSafwanAhmad 
  Did you resolve this error?

**Comment by Harshithasriniv** [comment]
i am also trying to run  the shubham 's rep ,i am also getting the same error.if  you resolved this error can you please tell me the solution

**Comment by shubham0204** [comment]
Have you downloaded the dataset and change the value of `image_dir` in `DataProcessor.py`?

**Comment by Harshithasriniv** [comment]
I have my own dataset and I'm applying this model for that dataset

**Comment by abhrodeep** [comment]
I also had the same problem, but my solution was to change the name of the parent folder where all your dataset, python script, model, label files are to something simple and try. Try it and tell me

**Comment by shubham0204** [comment]
If you all are facing issues regarding the files/folder, try using the [Colab notebook](https://colab.research.google.com/drive/1usT_XYE6DLENeUL3__GNCYAWn-0NbVh6#forceEdit=true&sandboxMode=true). You may download the Jupyter notebook from Colab and run it on your machine.
